services:
  app:
    image: ${IMAGE:-ghcr.io/nayleen/bunny-ddns}:${IMAGE_TAG:-latest}
    build:
      context: .
    env_file: .env
    environment:
      LOG_LEVEL: debug
      PHP_INI_TEMPLATE_FILE: development
      UPDATE_INTERVAL: 10
      XDEBUG_MODE: debug,develop
    network_mode: host
    restart: on-failure
    volumes:
      - $HOME/.composer:/app/var/composer
      - ./:/app/src
